### ISSUE TITLE
Please link ahocorasick code into libparaglob

### ISSUE THREAD

**Issue by hillu** [zeek/paraglob#16]
The problem I tried to solve with 1df272d10abd07a7938f0f3993f50cb8eb882116 (part of #14) was that linking libparaglob into an executable would fail because of undefined references, e.g.:
> undefined reference to `AhoCorasickPlus::AhoCorasickPlus()'

This problem does not exist when building libparaglob as part of a larger CMake-based project (such as Zeek), I believe that in that case CMake takes the `target_link_libraries` statement into account.

**Comment by jsiwek** [comment]
Thanks for the explanation, fix now in master branch via 7ffa364
